spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_hkbpCMS?stringtype=unspecified
    username: postgres
    password: HKBP_CMS
  application:
    name: CMS
    version: 1.0.0
  frontend: "*"
  devtools:
    add-properties: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        id:
          uuid:
            generator: org.hibernate.id.UUIDGenerator
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
minio:
  url: url-minio
  port: port-minio
  access_key: access_key
  secret-key: secret-key
  bucket: "cms-project"
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
baseUrl: https://api-prod.cms.co.id/



